"""Cosine vs FLAG-MD, with and without the finetuned variant, per backbone, next to the paper's Table 4.

    PYTHONPATH=. python -m scripts.analyze.build_cosine_vs_md_comparison

Reads results/main/** (+ results/main_gpu/** overriding duplicates) and research/reported_results.csv.
Writes results/cosine_vs_md_comparison.{md,csv}. No training is run.
The paper has no FLAG-MD, so paper numbers only exist for baseline / flag / flag_finetuned under cosine.
"""
from __future__ import annotations
import csv, glob, json, pathlib
import numpy as np
from scipy import stats

ROOT = pathlib.Path(__file__).resolve().parents[2]
DATASETS = ["reddit", "instagram", "amazon_text", "amazon_video_text", "yelpchi_text"]
MODELS = ["gcn", "gat", "geniepath", "care_gnn", "bwgnn", "dga_gnn", "pmp"]
COLS = [("baseline", "none"), ("flag", "cosine"), ("flag", "md_K2_matched"),
        ("flag_finetuned", "cosine"), ("flag_finetuned", "md_K2_matched")]
HEAD = ["baseline", "flag·cos", "flag·MD", "flag*·cos", "flag*·MD"]

runs = {}
for root in ("results/main", "results/main_gpu"):  # GPU twins override CPU duplicates
    for f in sorted(glob.glob(str(ROOT / root / "*" / "*" / "*.json"))):
        d = json.load(open(f))
        if d.get("status") != "completed":
            continue
        sam = pathlib.Path(f).parent.name
        if d["variant"] == "baseline":
            sam = "none"
        runs[(d["dataset"], d["model"], d["variant"], sam, d["seed"], d["initialization"])] = d

def vals(ds, m, v, s, metric):
    return {(k[4], k[5]): x[metric] * 100 for k, x in runs.items() if k[:4] == (ds, m, v, s)}

paper = {}
for r in csv.DictReader(open(ROOT / "research/reported_results.csv")):
    if r["source_table"] == "Table 4":
        paper[(r["dataset"], r["model"], r["variant"], r["metric"])] = float(r["mean"])

rows, md = [], []
for metric, label in (("test_auc", "AUC"), ("test_f1_macro", "F1-macro")):
    pm = "auc" if metric == "test_auc" else "f1_macro"
    for ds in DATASETS:
        md += [f"\n### {ds} — {label} (mean over 25 runs, %)\n",
               "| Backbone | " + " | ".join(HEAD) + " | MD−cos (flag) | MD−cos (flag*) | paper flag | paper flag* | ours flag−paper |",
               "|---|" + "---:|" * 10]
        agg = {c: [] for c in COLS}
        for m in MODELS:
            cells, means = [], {}
            for c in COLS:
                v = vals(ds, m, c[0], c[1], metric)
                means[c] = np.mean(list(v.values())) if v else float("nan")
                agg[c].append(means[c])
                cells.append(f"{means[c]:.2f}" if v else "–")
                rows.append(dict(dataset=ds, model=m, metric=label, variant=c[0], sampler=c[1], n=len(v),
                                 mean=round(means[c], 3) if v else "", std=round(float(np.std(list(v.values()), ddof=1)), 3) if v else ""))
            dl = []
            for var in ("flag", "flag_finetuned"):
                a, b = vals(ds, m, var, "cosine", metric), vals(ds, m, var, "md_K2_matched", metric)
                ks = sorted(set(a) & set(b))
                if len(ks) > 1:
                    x = np.array([b[k] - a[k] for k in ks])
                    p = stats.ttest_rel([b[k] for k in ks], [a[k] for k in ks]).pvalue if x.std() > 0 else 1.0
                    dl.append(f"{x.mean():+.2f}{'*' if p < 0.05 else ''}")
                else:
                    dl.append("–")
            pf, pfs = paper.get((ds, m, "flag", pm)), paper.get((ds, m, "flag_finetuned", pm))
            gap = f"{means[COLS[1]] - pf:+.2f}" if pf is not None else "–"
            md.append(f"| {m} | " + " | ".join(cells) + f" | {dl[0]} | {dl[1]} | "
                      f"{pf if pf is not None else '–'} | {pfs if pfs is not None else '–'} | {gap} |")
        avg = [np.nanmean(agg[c]) for c in COLS]
        md.append("| **mean** | " + " | ".join(f"**{x:.2f}**" for x in avg) +
                  f" | **{avg[2]-avg[1]:+.2f}** | **{avg[4]-avg[3]:+.2f}** | | | |")

head = f"""# Cosine vs FLAG-MD, with and without finetuning

Columns: `baseline`; `flag` (zero-shot LLM text) and `flag*` (= `flag_finetuned`), each with the paper's cosine sampler and with FLAG-MD (K=2 matched).
`MD−cos` is the mean paired difference over the 25 (seed, init) pairs; `*` marks a paired t-test p < 0.05.
Paper columns are Table 4 means from `research/reported_results.csv` (transcribed, second-hand; the PDF is not in the repo).
The paper has no FLAG-MD, and has no numbers for Amazon, YelpChi or Amazon Video, so those cells are `–`.
`flag*` here keeps the LLM frozen (decision D-001), so it is not LLM fine-tuning. Generated by `scripts/analyze/build_cosine_vs_md_comparison.py`.
"""
(ROOT / "results/cosine_vs_md_comparison.md").write_text(head + "\n".join(md) + "\n", encoding="utf-8")
with open(ROOT / "results/cosine_vs_md_comparison.csv", "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
print(f"{len(runs)} runs -> results/cosine_vs_md_comparison.md")
